apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Maharashtra1998@
        - name: MYSQL_DATABASE
          value: sampledb
        - name: MYSQL_USER
          value: dinesh
        - name: MYSQL_PASSWORD
          value: H@Sh1CoR3!
        ports:
        - containerPort: 3306
          name: db
        
