apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: dineshmk/node-app:dinesh                 
        ports:
        - containerPort: 80
          name: webapp
        env:
        - name: DB_HOST
          value: db-deployment
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: dineshdb
        - name: DB_USER
          value: dinesh
        - name: DB_PASSWORD
          value: H@Sh1CoR3!
        
